/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SkillsTestRouteImport } from './routes/skills-test'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FastServicesRouteImport } from './routes/fast-services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIdRouteImport } from './routes/services.$id'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PaymentCancelledRouteImport } from './routes/payment.cancelled'
import { Route as DashboardSellerRouteImport } from './routes/dashboard.seller'
import { Route as DashboardBuyerRouteImport } from './routes/dashboard.buyer'
import { Route as CategoriesCategoryRouteImport } from './routes/categories.$category'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsTestRoute = SkillsTestRouteImport.update({
  id: '/skills-test',
  path: '/skills-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FastServicesRoute = FastServicesRouteImport.update({
  id: '/fast-services',
  path: '/fast-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ServicesRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelledRoute = PaymentCancelledRouteImport.update({
  id: '/payment/cancelled',
  path: '/payment/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSellerRoute = DashboardSellerRouteImport.update({
  id: '/dashboard/seller',
  path: '/dashboard/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuyerRoute = DashboardBuyerRouteImport.update({
  id: '/dashboard/buyer',
  path: '/dashboard/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryRoute = CategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/fast-services': typeof FastServicesRoute
  '/help': typeof HelpRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRouteWithChildren
  '/skills-test': typeof SkillsTestRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/payment/cancelled': typeof PaymentCancelledRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/fast-services': typeof FastServicesRoute
  '/help': typeof HelpRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRouteWithChildren
  '/skills-test': typeof SkillsTestRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/payment/cancelled': typeof PaymentCancelledRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/fast-services': typeof FastServicesRoute
  '/help': typeof HelpRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRouteWithChildren
  '/skills-test': typeof SkillsTestRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/payment/cancelled': typeof PaymentCancelledRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/fast-services'
    | '/help'
    | '/mcp'
    | '/messages'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/security'
    | '/services'
    | '/skills-test'
    | '/terms'
    | '/wallet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/categories/$category'
    | '/dashboard/buyer'
    | '/dashboard/seller'
    | '/payment/cancelled'
    | '/payment/success'
    | '/projects/$id'
    | '/services/$id'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/fast-services'
    | '/help'
    | '/mcp'
    | '/messages'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/security'
    | '/services'
    | '/skills-test'
    | '/terms'
    | '/wallet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/categories/$category'
    | '/dashboard/buyer'
    | '/dashboard/seller'
    | '/payment/cancelled'
    | '/payment/success'
    | '/projects/$id'
    | '/services/$id'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/fast-services'
    | '/help'
    | '/mcp'
    | '/messages'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/security'
    | '/services'
    | '/skills-test'
    | '/terms'
    | '/wallet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/categories/$category'
    | '/dashboard/buyer'
    | '/dashboard/seller'
    | '/payment/cancelled'
    | '/payment/success'
    | '/projects/$id'
    | '/services/$id'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FastServicesRoute: typeof FastServicesRoute
  HelpRoute: typeof HelpRoute
  McpRoute: typeof McpRoute
  MessagesRoute: typeof MessagesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SkillsTestRoute: typeof SkillsTestRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CategoriesCategoryRoute: typeof CategoriesCategoryRoute
  DashboardBuyerRoute: typeof DashboardBuyerRoute
  DashboardSellerRoute: typeof DashboardSellerRoute
  PaymentCancelledRoute: typeof PaymentCancelledRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills-test': {
      id: '/skills-test'
      path: '/skills-test'
      fullPath: '/skills-test'
      preLoaderRoute: typeof SkillsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fast-services': {
      id: '/fast-services'
      path: '/fast-services'
      fullPath: '/fast-services'
      preLoaderRoute: typeof FastServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancelled': {
      id: '/payment/cancelled'
      path: '/payment/cancelled'
      fullPath: '/payment/cancelled'
      preLoaderRoute: typeof PaymentCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seller': {
      id: '/dashboard/seller'
      path: '/dashboard/seller'
      fullPath: '/dashboard/seller'
      preLoaderRoute: typeof DashboardSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/dashboard/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$category': {
      id: '/categories/$category'
      path: '/categories/$category'
      fullPath: '/categories/$category'
      preLoaderRoute: typeof CategoriesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesIdRoute: typeof ServicesIdRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesIdRoute: ServicesIdRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FastServicesRoute: FastServicesRoute,
  HelpRoute: HelpRoute,
  McpRoute: McpRoute,
  MessagesRoute: MessagesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SkillsTestRoute: SkillsTestRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CategoriesCategoryRoute: CategoriesCategoryRoute,
  DashboardBuyerRoute: DashboardBuyerRoute,
  DashboardSellerRoute: DashboardSellerRoute,
  PaymentCancelledRoute: PaymentCancelledRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
