-- Migration history baseline marker.
-- Production already contains the change recorded as 20260925152104 (remove_unused_order_notification_rpc).
-- Kept as a no-op so the repository migration history matches the production history.
