-- Migration history baseline marker.
-- Production already contains the change recorded as 20260925153248 (revoke_profile_protection_execute_public).
-- Kept as a no-op so the repository migration history matches the production history.
